services:
  - type: web
    name: internfind-django
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn InternFind.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: InternFind.settings
      - key: PYTHON_VERSION
        value: 3.10
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "internfind.onrender.com"
    staticPublishPath: staticfiles
    autoDeploy: true
